### ISSUE TITLE
Links in footer are not in a logical order and some are missing

### ISSUE THREAD

**Issue by Tajana-Somogyi** [ALASdoo/alasdoo_com_v2#39]
- [x] Remove Home link
- [x] new link order (after the nav links are changed, see issue #32):
1. Services
2. Our story
3. Our team
4. Our clients
5. Case studies
6. Careers
7. Articles
8. Contact us
- [x] Use the same formating for Contact us as for the other links (currently, hover state fails color contrast)
- [x] Change separator color to #313131D
- [x] Change copyright text to: "© 2024 ALAS doo” (copyright symbol written as &copy;)
- [x] Chenge copyright text size to 16px
- [x] Change copyright font color to rgba(49, 49, 49, 0.85)—#313131D
- [x] Move copyright notice to the left
- [x] On the right—in the line with the copyright notice—add links: Accessibility statement I Cookies I Privacy policy
- [ ] #111
